[package]
name = "omni-transaction"
version = "0.3.2"
authors = ["Proximity Labs Limited"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/near/omni-transaction-rs"
description = "Transaction builder for all chains in Rust"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[features]
default = ["all", "serde", "serde_json", "schemars"]
all = ["near", "bitcoin", "evm"]
bitcoin = ["sha2"]
evm = ["dep:rlp"]
near = ["dep:near-account-id", "dep:bs58", "borsh"]
borsh = ["dep:borsh", "near-account-id/borsh"]
serde = ["dep:serde", "dep:serde-big-array", "dep:base64", "near-account-id/serde"]
serde_json = ["dep:serde_json", "serde"]
schemars = ["dep:schemars", "near-account-id/schemars-v1"]

[dependencies]
serde_json = { version = "1.0", optional = true }
rlp = { version = "0.6.1", optional = true }
hex = "0.4.3"
borsh = { version = "1.0.0", features = ["derive"], optional = true }
near-account-id = { version = "2", optional = true }
serde-big-array = { version = "0.5.1", optional = true }
bs58 = { version = "0.5.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
schemars = { version = "1.0", optional = true }
sha2 = { version = "0.10.8", optional = true }
base64 = { version = "0.22", optional = true }


[dev-dependencies]
# ethereum
alloy = { version = "0.3.3", features = ["full", "node-bindings", "rlp"] }
alloy-rlp = { version = "0.3.8", features = ["derive"] }
alloy-primitives = { version = "0.8.3" }

# near
near-primitives = { version = "0.34" }
near-crypto = { version = "0.34" }
near-jsonrpc-client = { version = "0.20", features = ["any"] }
near-workspaces = { version = "0.22", features = ["experimental", "unstable"] }
serde_json = { version = "1.0" }
sha2 = { version = "0.10.8" }
base64 = { version = "0.22" }

# bitcoin
bitcoin = { version = "0.32.0", default-features = false, features = [
    "std",
    "serde",
    "rand-std",
    "rand",
    "secp-lowmemory",
    "secp-recovery",
] }
k256 = { version = "0.13.1", features = [
    "sha256",
    "ecdsa",
    "serde",
    "arithmetic",
    "expose-field",
] }

# async
tokio = { version = "1.38", features = ["full"] }

# misc
eyre = "0.6"

# testing
omni-testing-utilities = { git = "https://github.com/near/omni-testing-utilities", branch = "main" }
