#![cfg(feature = "zcash")]
//! End-to-end Zcash tests: builder -> build_for_signing -> sign (k256) ->
//! build_with_signature, verified byte-for-byte against reference vectors.
use k256::ecdsa::signature::hazmat::{PrehashSigner, PrehashVerifier};
use k256::ecdsa::{Signature, SigningKey, VerifyingKey};

use omni_transaction::zcash::types::{
    Amount, ConsensusBranchId, Hash, OutPoint, ScriptBuf, Sequence, SpentUtxo, TxIn, TxOut, Txid,
    Witness, ZcashSighashType,
};
use omni_transaction::zcash::utils::p2pkh_script_sig;
use omni_transaction::{TransactionBuilder, TxBuilder, ZCASH};

/// Transparent-only end-to-end vector, generated by an independent
/// implementation of ZIP-225/244 that reproduces all 10 official
/// zcash-test-vectors zip_0244 vectors byte-for-byte.
const E2E_UNSIGNED_HEX: &str = "050000800a27a7265b16a53700000000a025260001000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f0100000000feffffff02f0b9f505000000001976a9148132712c3ff19f3a151234616777420a6d7ef22688ac881300000000000017a914ad63d2abbb1395c6a8bbdac575cca6e6e63a1e1c87000000";
const E2E_SIGHASH_ALL_HEX: &str =
    "e057d65831080c539cb2eb9ae99a5b33799b38964e56c968a9922afb8a93c883";
const E2E_TXID_INTERNAL_HEX: &str =
    "982ac085f6fd0dc814bc1ef302551fd530585704fe698b820a3ceb026171b8e0";
const E2E_TXID_DISPLAY_HEX: &str =
    "e0b8716102eb3c0a828b69fe04575830d51f5502f31ebc14c80dfdf685c02a98";
const E2E_SCRIPT_SIG_HEX: &str = "4830450221111111111111111111111111111111111111111111111111111111111111111111022022222222222222222222222222222222222222222222222222222222222222220121023333333333333333333333333333333333333333333333333333333333333333";
const E2E_SIGNED_HEX: &str = "050000800a27a7265b16a53700000000a025260001000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f010000006b4830450221111111111111111111111111111111111111111111111111111111111111111111022022222222222222222222222222222222222222222222222222222222222222220121023333333333333333333333333333333333333333333333333333333333333333feffffff02f0b9f505000000001976a9148132712c3ff19f3a151234616777420a6d7ef22688ac881300000000000017a914ad63d2abbb1395c6a8bbdac575cca6e6e63a1e1c87000000";

/// Byte offset of input 0's script sig CompactSize in the unsigned
/// serialization: 20-byte header block + 1-byte input count + 36-byte
/// outpoint.
const SCRIPT_SIG_OFFSET: usize = 20 + 1 + 36;

/// Builds a `TxIn` whose previous txid is given in *internal* (wire) byte
/// order. `Hash` stores display-order bytes, so they are reversed here.
fn txin_from_internal_txid(txid_internal_hex: &str, vout: u32, sequence: u32) -> TxIn {
    let mut bytes: [u8; 32] = hex::decode(txid_internal_hex).unwrap().try_into().unwrap();
    bytes.reverse();
    TxIn {
        previous_output: OutPoint::new(Txid(Hash(bytes)), vout),
        script_sig: ScriptBuf::default(),
        sequence: Sequence(sequence),
        witness: Witness::default(),
    }
}

fn build_end_to_end_tx() -> omni_transaction::zcash::ZcashTransaction {
    let input = txin_from_internal_txid(
        "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
        1,
        0xFFFF_FFFE,
    );
    let outputs = vec![
        TxOut {
            value: Amount::from_sat(99_990_000),
            script_pubkey: ScriptBuf::from_hex(
                "76a9148132712c3ff19f3a151234616777420a6d7ef22688ac",
            )
            .unwrap(),
        },
        TxOut {
            value: Amount::from_sat(5_000),
            script_pubkey: ScriptBuf::from_hex("a914ad63d2abbb1395c6a8bbdac575cca6e6e63a1e1c87")
                .unwrap(),
        },
    ];

    TransactionBuilder::new::<ZCASH>()
        .consensus_branch_id(ConsensusBranchId::Nu6_3)
        .lock_time(0)
        .expiry_height(2_500_000)
        .inputs(vec![input])
        .outputs(outputs)
        .build()
}

fn spent_utxos() -> Vec<SpentUtxo> {
    vec![SpentUtxo::new(
        100_000_000,
        ScriptBuf::from_hex("76a914507173527b4c3318a2aecd793bf1cfed705950cf88ac").unwrap(),
    )]
}

#[test]
fn test_builder_produces_reference_unsigned_serialization() {
    let tx = build_end_to_end_tx();
    assert_eq!(hex::encode(tx.serialize()), E2E_UNSIGNED_HEX);
}

#[test]
fn test_builder_produces_reference_txid() {
    let tx = build_end_to_end_tx();
    let txid = tx.txid();
    assert_eq!(hex::encode(txid), E2E_TXID_INTERNAL_HEX);

    let mut display = txid;
    display.reverse();
    assert_eq!(hex::encode(display), E2E_TXID_DISPLAY_HEX);
}

#[test]
fn test_build_for_signing_produces_reference_sighash() {
    let tx = build_end_to_end_tx();
    let sighash = tx.build_for_signing(0, ZcashSighashType::All, &spent_utxos());
    assert_eq!(hex::encode(sighash), E2E_SIGHASH_ALL_HEX);
}

#[test]
fn test_build_with_signature_produces_reference_signed_serialization() {
    let mut tx = build_end_to_end_tx();
    let script_sig = ScriptBuf::from_hex(E2E_SCRIPT_SIG_HEX).unwrap();
    let signed = tx.build_with_signature(0, script_sig);
    assert_eq!(hex::encode(signed), E2E_SIGNED_HEX);
}

/// Full flow: builder -> build_for_signing -> ECDSA sign over the 32-byte
/// ZIP-244 sighash (k256, low-S, strict DER) -> p2pkh_script_sig ->
/// build_with_signature; the result is verified byte-for-byte against an
/// independently spliced serialization, and the signature is verified against
/// the sighash with the reference implementation.
#[test]
fn test_end_to_end_sign_and_serialize_with_k256() {
    let mut tx = build_end_to_end_tx();
    let unsigned = tx.serialize();
    assert_eq!(hex::encode(&unsigned), E2E_UNSIGNED_HEX);

    // 1. The final 32-byte sighash; signed directly, with no extra hashing.
    let sighash = tx.build_for_signing(0, ZcashSighashType::All, &spent_utxos());
    assert_eq!(hex::encode(&sighash), E2E_SIGHASH_ALL_HEX);

    // 2. Sign the digest with a fixed key (as the NEAR MPC signer would).
    let signing_key = SigningKey::from_bytes((&[0x11u8; 32]).into()).unwrap();
    let signature: Signature = signing_key.sign_prehash(&sighash).unwrap();
    // Low-S normalize (zcashd standardness rule).
    let signature = signature.normalize_s().unwrap_or(signature);

    // 3. Verify the signature over the exact digest with the reference
    // implementation (k256), proving no extra hashing step is involved.
    let verifying_key = VerifyingKey::from(&signing_key);
    verifying_key
        .verify_prehash(&sighash, &signature)
        .expect("signature must verify over the ZIP-244 sighash");

    // 4. Strict DER + hash type byte, then the P2PKH script sig.
    let mut sig_with_hashtype = signature.to_der().as_bytes().to_vec();
    sig_with_hashtype.push(ZcashSighashType::All.to_u8());
    assert!((71..=73).contains(&sig_with_hashtype.len()));

    let pubkey = verifying_key.to_encoded_point(true).as_bytes().to_vec();
    assert_eq!(pubkey.len(), 33);

    let script_sig = p2pkh_script_sig(&sig_with_hashtype, &pubkey);

    // 5. Independently splice the script sig into the unsigned serialization:
    // the empty script sig (a single 0x00 CompactSize) is replaced by
    // `CompactSize(len) || script_sig`.
    assert_eq!(unsigned[SCRIPT_SIG_OFFSET], 0x00);
    assert!(script_sig.0.len() < 0xFD);
    let mut expected = Vec::with_capacity(unsigned.len() + script_sig.0.len());
    expected.extend_from_slice(&unsigned[..SCRIPT_SIG_OFFSET]);
    expected.push(script_sig.0.len() as u8);
    expected.extend_from_slice(&script_sig.0);
    expected.extend_from_slice(&unsigned[SCRIPT_SIG_OFFSET + 1..]);

    let signed = tx.build_with_signature(0, script_sig);
    assert_eq!(signed, expected);

    // 6. The txid does not depend on the script sig (ZIP-244 non-malleability).
    assert_eq!(hex::encode(tx.txid()), E2E_TXID_INTERNAL_HEX);
}

/// The sighash must change with the spent coin data (ZIP-244 S.2c/S.2d/S.2g),
/// so stale UTXO data cannot silently produce the same digest.
#[test]
fn test_sighash_commits_to_spent_utxo_data() {
    let tx = build_end_to_end_tx();
    let reference = tx.build_for_signing(0, ZcashSighashType::All, &spent_utxos());

    let wrong_value = vec![SpentUtxo::new(
        100_000_001,
        ScriptBuf::from_hex("76a914507173527b4c3318a2aecd793bf1cfed705950cf88ac").unwrap(),
    )];
    assert_ne!(
        tx.build_for_signing(0, ZcashSighashType::All, &wrong_value),
        reference
    );

    let wrong_script = vec![SpentUtxo::new(
        100_000_000,
        ScriptBuf::from_hex("76a914507173527b4c3318a2aecd793bf1cfed705950cf88ad").unwrap(),
    )];
    assert_ne!(
        tx.build_for_signing(0, ZcashSighashType::All, &wrong_script),
        reference
    );
}

/// The sighash must change with the consensus branch id, which is part of the
/// BLAKE2b personalization of the top-level digest.
#[test]
fn test_sighash_commits_to_consensus_branch_id() {
    let tx_nu6_3 = build_end_to_end_tx();
    let mut tx_nu5 = tx_nu6_3.clone();
    tx_nu5.consensus_branch_id = ConsensusBranchId::Nu5;

    assert_ne!(
        tx_nu5.build_for_signing(0, ZcashSighashType::All, &spent_utxos()),
        tx_nu6_3.build_for_signing(0, ZcashSighashType::All, &spent_utxos())
    );
    assert_ne!(tx_nu5.txid(), tx_nu6_3.txid());
}
